"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
sys.setrecursionlimit(1500)
APP = ['fesyen.py']
DATA_FILES = []
OPTIONS = {
           'plist': {
               'PyRuntimeLocations': [
                '/Users/migellamp/opt/anaconda3/envs/py36/lib/libpython3.6m.dylib',
                '/Users/migellamp/opt/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/_checkpoint_ops.so',
               ]
           },
           'packages':['tensorflow','segment','pygments','shapely','rtree','pywt','skimage','cv2','h5py'],
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# ln -s /Users/migellamp/opt/anaconda3/envs/py36/lib/libpython3.6m.dylib /Users/migellamp/opt/anaconda3/envs/py36/lib/libpython3.6.dylib